/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * Values: booked,already_booked,clarification_required,not_found,dismissed
 */
@Serializable
enum class OfflineBookingStatus(val value: kotlin.String) {

    @SerialName(value = "booked")
    booked("booked"),

    @SerialName(value = "already_booked")
    already_booked("already_booked"),

    @SerialName(value = "clarification_required")
    clarification_required("clarification_required"),

    @SerialName(value = "not_found")
    not_found("not_found"),

    @SerialName(value = "dismissed")
    dismissed("dismissed");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OfflineBookingStatus) "$data" else null

        /**
         * Returns a valid [OfflineBookingStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OfflineBookingStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

