/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.CompletedSale
import de.stustapay.api.models.OfflineBookingStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param uuid 
 * @param status 
 * @param sale 
 * @param message 
 */
@Serializable

data class OfflineBookingResult (

    @Contextual @SerialName(value = "uuid")
    val uuid: java.util.UUID,

    @Contextual @SerialName(value = "status")
    val status: OfflineBookingStatus,

    @SerialName(value = "sale")
    val sale: CompletedSale? = null,

    @SerialName(value = "message")
    val message: kotlin.String? = null

) {


}

