/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.NewSale

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param snapshotId 
 * @param sale 
 * @param sequence 
 * @param recordedAt 
 */
@Serializable

data class OfflineBooking (

    @Contextual @SerialName(value = "snapshot_id")
    val snapshotId: java.util.UUID,

    @SerialName(value = "sale")
    val sale: NewSale,

    @SerialName(value = "sequence")
    val sequence: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @Contextual @SerialName(value = "recorded_at")
    val recordedAt: java.time.OffsetDateTime

) {


}

