/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.OfflineButton
import de.stustapay.api.models.OfflineCustomer
import de.stustapay.api.models.OfflineLimits

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param serverTime 
 * @param validUntil 
 * @param terminalId 
 * @param tillId 
 * @param eventNodeId 
 * @param userId 
 * @param rules 
 * @param customers 
 * @param buttons 
 */
@Serializable

data class OfflineSnapshot (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "server_time")
    val serverTime: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "valid_until")
    val validUntil: java.time.OffsetDateTime,

    @SerialName(value = "terminal_id")
    val terminalId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "till_id")
    val tillId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "event_node_id")
    val eventNodeId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "user_id")
    val userId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "rules")
    val rules: OfflineLimits,

    @SerialName(value = "customers")
    val customers: kotlin.collections.List<OfflineCustomer>,

    @SerialName(value = "buttons")
    val buttons: kotlin.collections.List<OfflineButton>

) {


}

