/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param validitySeconds 
 * @param salePerTransactionCents 
 * @param salePerCustomerCents 
 * @param salePerTillCents 
 * @param returnPerTransactionCents 
 * @param returnPerCustomerCents 
 * @param returnPerTillCents 
 */
@Serializable

data class OfflineLimits (

    @SerialName(value = "validity_seconds")
    val validitySeconds: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = com.ionspin.kotlin.bignum.integer.BigInteger(7200),

    @SerialName(value = "sale_per_transaction_cents")
    val salePerTransactionCents: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = com.ionspin.kotlin.bignum.integer.BigInteger(2000),

    @SerialName(value = "sale_per_customer_cents")
    val salePerCustomerCents: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = com.ionspin.kotlin.bignum.integer.BigInteger(3000),

    @SerialName(value = "sale_per_till_cents")
    val salePerTillCents: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = com.ionspin.kotlin.bignum.integer.BigInteger(50000),

    @SerialName(value = "return_per_transaction_cents")
    val returnPerTransactionCents: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = com.ionspin.kotlin.bignum.integer.BigInteger(2000),

    @SerialName(value = "return_per_customer_cents")
    val returnPerCustomerCents: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = com.ionspin.kotlin.bignum.integer.BigInteger(3000),

    @SerialName(value = "return_per_till_cents")
    val returnPerTillCents: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = com.ionspin.kotlin.bignum.integer.BigInteger(50000)

) {


}

